baseURL: https://covid-spark.info/
markup:
  goldmark:
    renderer:
      unsafe: true
languageCode: sl
title: SPARK
disableKinds:
  - categories
  - tags
defaultContentLanguage: sl
params:
  siteVersion: 1.1
languages:
  sl:
    params:
      linkSledilnik: https://covid-19.sledilnik.org/sl
      version: Verzija
    title: SPARK
    weight: 1
    languageName: Slovenščina
  en:
    params:
      linkSledilnik: https://covid-19.sledilnik.org/en
      version: Version
    title: SPARK (English)
    weight: 2
    languageName: English
