name: Build and deploy (stagging)

on:
  push:
    branches:
      - master

env:
  RELEASE_NAME: spark
  CHART_VALUES_FILE: .helm/values.stage.yml
  DEPLOY_NAMESPACE: spark-stage
  DEPLOY_ENV: stagging
  DEPLOY_URL: https://stage.covid-spark.info

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Build and push docker container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/spark:latest

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    if: "!contains(github.event.head_commit.message, 'NODEPLOY')"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy
        uses: sledilnik/action-helm-deploy@master
        with:
          chartName: sledilnik/spark
          chartVersion: '0.9.0'
          kubeconfig: '${{ secrets.KUBECONFIG }}'   